// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fingerprint.sql

package db

import (
	"context"
)

const createFingerPrint = `-- name: CreateFingerPrint :one
insert into fingerprint (statistics_id, ip) values ($1, $2) returning id, statistics_id, ip, created_at
`

type CreateFingerPrintParams struct {
	StatisticsID int64  `json:"statistics_id"`
	Ip           string `json:"ip"`
}

func (q *Queries) CreateFingerPrint(ctx context.Context, arg CreateFingerPrintParams) (*Fingerprint, error) {
	row := q.db.QueryRow(ctx, createFingerPrint, arg.StatisticsID, arg.Ip)
	var i Fingerprint
	err := row.Scan(
		&i.ID,
		&i.StatisticsID,
		&i.Ip,
		&i.CreatedAt,
	)
	return &i, err
}

const getFingerPrintByIp = `-- name: GetFingerPrintByIp :one
select id, statistics_id, ip, created_at from fingerprint where ip = $1 order by id
`

func (q *Queries) GetFingerPrintByIp(ctx context.Context, ip string) (*Fingerprint, error) {
	row := q.db.QueryRow(ctx, getFingerPrintByIp, ip)
	var i Fingerprint
	err := row.Scan(
		&i.ID,
		&i.StatisticsID,
		&i.Ip,
		&i.CreatedAt,
	)
	return &i, err
}

const getFingerPrints = `-- name: GetFingerPrints :many
select id, statistics_id, ip, created_at from fingerprint order by id
`

func (q *Queries) GetFingerPrints(ctx context.Context) ([]*Fingerprint, error) {
	rows, err := q.db.Query(ctx, getFingerPrints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Fingerprint
	for rows.Next() {
		var i Fingerprint
		if err := rows.Scan(
			&i.ID,
			&i.StatisticsID,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFullFingerPrintById = `-- name: GetFullFingerPrintById :one
select
    fp.id, fp.statistics_id, fp.ip, fp.created_at,
    ua.id, ua.fingerprint_id, ua.agent, ua.last_accessed
from fingerprint fp join user_agents ua on fp.id = ua.fingerprint_id where fp.id = $1
`

type GetFullFingerPrintByIdRow struct {
	Fingerprint Fingerprint `json:"fingerprint"`
	UserAgent   UserAgent   `json:"user_agent"`
}

func (q *Queries) GetFullFingerPrintById(ctx context.Context, id int64) (*GetFullFingerPrintByIdRow, error) {
	row := q.db.QueryRow(ctx, getFullFingerPrintById, id)
	var i GetFullFingerPrintByIdRow
	err := row.Scan(
		&i.Fingerprint.ID,
		&i.Fingerprint.StatisticsID,
		&i.Fingerprint.Ip,
		&i.Fingerprint.CreatedAt,
		&i.UserAgent.ID,
		&i.UserAgent.FingerprintID,
		&i.UserAgent.Agent,
		&i.UserAgent.LastAccessed,
	)
	return &i, err
}

const getFullFingerPrintByIp = `-- name: GetFullFingerPrintByIp :one
select
    fp.id, fp.statistics_id, fp.ip, fp.created_at,
    ua.id, ua.fingerprint_id, ua.agent, ua.last_accessed
from fingerprint fp join user_agents ua on fp.id = ua.fingerprint_id where fp.ip = $1
`

type GetFullFingerPrintByIpRow struct {
	Fingerprint Fingerprint `json:"fingerprint"`
	UserAgent   UserAgent   `json:"user_agent"`
}

func (q *Queries) GetFullFingerPrintByIp(ctx context.Context, ip string) (*GetFullFingerPrintByIpRow, error) {
	row := q.db.QueryRow(ctx, getFullFingerPrintByIp, ip)
	var i GetFullFingerPrintByIpRow
	err := row.Scan(
		&i.Fingerprint.ID,
		&i.Fingerprint.StatisticsID,
		&i.Fingerprint.Ip,
		&i.Fingerprint.CreatedAt,
		&i.UserAgent.ID,
		&i.UserAgent.FingerprintID,
		&i.UserAgent.Agent,
		&i.UserAgent.LastAccessed,
	)
	return &i, err
}

const getFullFingerPrintByStatisticsId = `-- name: GetFullFingerPrintByStatisticsId :one
select
    fp.id, fp.statistics_id, fp.ip, fp.created_at,
    ua.id, ua.fingerprint_id, ua.agent, ua.last_accessed
from fingerprint fp join user_agents ua on fp.id = ua.fingerprint_id where fp.statistics_id = $1
`

type GetFullFingerPrintByStatisticsIdRow struct {
	Fingerprint Fingerprint `json:"fingerprint"`
	UserAgent   UserAgent   `json:"user_agent"`
}

func (q *Queries) GetFullFingerPrintByStatisticsId(ctx context.Context, statisticsID int64) (*GetFullFingerPrintByStatisticsIdRow, error) {
	row := q.db.QueryRow(ctx, getFullFingerPrintByStatisticsId, statisticsID)
	var i GetFullFingerPrintByStatisticsIdRow
	err := row.Scan(
		&i.Fingerprint.ID,
		&i.Fingerprint.StatisticsID,
		&i.Fingerprint.Ip,
		&i.Fingerprint.CreatedAt,
		&i.UserAgent.ID,
		&i.UserAgent.FingerprintID,
		&i.UserAgent.Agent,
		&i.UserAgent.LastAccessed,
	)
	return &i, err
}

const listFingerPrint = `-- name: ListFingerPrint :many
select id, statistics_id, ip, created_at from fingerprint order by id limit $1 offset $2
`

type ListFingerPrintParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFingerPrint(ctx context.Context, arg ListFingerPrintParams) ([]*Fingerprint, error) {
	rows, err := q.db.Query(ctx, listFingerPrint, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Fingerprint
	for rows.Next() {
		var i Fingerprint
		if err := rows.Scan(
			&i.ID,
			&i.StatisticsID,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFingerPrintByStatisticsId = `-- name: ListFingerPrintByStatisticsId :many
select id, statistics_id, ip, created_at from fingerprint where statistics_id = $1 order by id limit $2 offset $3
`

type ListFingerPrintByStatisticsIdParams struct {
	StatisticsID int64 `json:"statistics_id"`
	Limit        int32 `json:"limit"`
	Offset       int32 `json:"offset"`
}

func (q *Queries) ListFingerPrintByStatisticsId(ctx context.Context, arg ListFingerPrintByStatisticsIdParams) ([]*Fingerprint, error) {
	rows, err := q.db.Query(ctx, listFingerPrintByStatisticsId, arg.StatisticsID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Fingerprint
	for rows.Next() {
		var i Fingerprint
		if err := rows.Scan(
			&i.ID,
			&i.StatisticsID,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
