// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Fingerprint struct {
	ID           int64              `json:"id"`
	StatisticsID int64              `json:"statistics_id"`
	Ip           string             `json:"ip"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Statistic struct {
	ID           int64              `json:"id"`
	UrlID        int64              `json:"url_id"`
	Clicks       int64              `json:"clicks"`
	LastAccessed pgtype.Timestamptz `json:"last_accessed"`
}

type Url struct {
	ID          int64              `json:"id"`
	OriginalUrl string             `json:"original_url"`
	ShortUrl    string             `json:"short_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type UserAgent struct {
	ID            int64              `json:"id"`
	FingerprintID int64              `json:"fingerprint_id"`
	Agent         string             `json:"agent"`
	LastAccessed  pgtype.Timestamptz `json:"last_accessed"`
}
