// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateFingerPrint(ctx context.Context, arg CreateFingerPrintParams) (*Fingerprint, error)
	CreateStatistics(ctx context.Context, urlID int64) (*Statistic, error)
	CreateUrl(ctx context.Context, arg CreateUrlParams) (*Url, error)
	CreateUserAgent(ctx context.Context, arg CreateUserAgentParams) (*UserAgent, error)
	DeleteUrlById(ctx context.Context, id int64) error
	DeleteUrlByShortUrl(ctx context.Context, shortUrl string) error
	GetFingerPrintByIp(ctx context.Context, ip string) (*Fingerprint, error)
	GetFingerPrints(ctx context.Context) ([]*Fingerprint, error)
	GetFullFingerPrintById(ctx context.Context, id int64) (*GetFullFingerPrintByIdRow, error)
	GetFullFingerPrintByIp(ctx context.Context, ip string) (*GetFullFingerPrintByIpRow, error)
	GetFullFingerPrintByStatisticsId(ctx context.Context, statisticsID int64) (*GetFullFingerPrintByStatisticsIdRow, error)
	GetOriginalUrlById(ctx context.Context, id int64) (string, error)
	GetOriginalUrlByShortUrl(ctx context.Context, shortUrl string) (string, error)
	GetStatisticById(ctx context.Context, id int64) (*Statistic, error)
	GetStatistics(ctx context.Context) ([]*Statistic, error)
	GetStatisticsByUrlId(ctx context.Context, urlID int64) (*Statistic, error)
	GetUrls(ctx context.Context) ([]*Url, error)
	GetUserAgentById(ctx context.Context, id int64) (*UserAgent, error)
	GetUserAgents(ctx context.Context) ([]*UserAgent, error)
	GetUserAgentsByFingerprintId(ctx context.Context, fingerprintID int64) ([]*UserAgent, error)
	IncrementClicksCountById(ctx context.Context, id int64) (*Statistic, error)
	IncrementClicksCountByUrlId(ctx context.Context, urlID int64) (*Statistic, error)
	ListFingerPrint(ctx context.Context, arg ListFingerPrintParams) ([]*Fingerprint, error)
	ListFingerPrintByStatisticsId(ctx context.Context, arg ListFingerPrintByStatisticsIdParams) ([]*Fingerprint, error)
	ListStatistics(ctx context.Context, arg ListStatisticsParams) ([]*Statistic, error)
	ListUrls(ctx context.Context, arg ListUrlsParams) ([]*Url, error)
	UpdateLastAccessedById(ctx context.Context, id int64) (*Statistic, error)
	UpdateStatisticsByUrlId(ctx context.Context, urlID int64) (*Statistic, error)
	UpdateUserAgentLastAccessedById(ctx context.Context, id int64) (*UserAgent, error)
}

var _ Querier = (*Queries)(nil)
