// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: statistics.sql

package db

import (
	"context"
)

const createStatistics = `-- name: CreateStatistics :one
insert into statistics (url_id) values ($1) returning id, url_id, clicks, last_accessed, created_at
`

func (q *Queries) CreateStatistics(ctx context.Context, urlID int64) (*Statistic, error) {
	row := q.db.QueryRow(ctx, createStatistics, urlID)
	var i Statistic
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.Clicks,
		&i.LastAccessed,
		&i.CreatedAt,
	)
	return &i, err
}

const getStatisticById = `-- name: GetStatisticById :one
select id, url_id, clicks, last_accessed, created_at from statistics where id = $1 order by id
`

func (q *Queries) GetStatisticById(ctx context.Context, id int64) (*Statistic, error) {
	row := q.db.QueryRow(ctx, getStatisticById, id)
	var i Statistic
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.Clicks,
		&i.LastAccessed,
		&i.CreatedAt,
	)
	return &i, err
}

const getStatistics = `-- name: GetStatistics :many
select id, url_id, clicks, last_accessed, created_at from statistics order by id
`

func (q *Queries) GetStatistics(ctx context.Context) ([]*Statistic, error) {
	rows, err := q.db.Query(ctx, getStatistics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Statistic
	for rows.Next() {
		var i Statistic
		if err := rows.Scan(
			&i.ID,
			&i.UrlID,
			&i.Clicks,
			&i.LastAccessed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatisticsByUrlId = `-- name: GetStatisticsByUrlId :one
select id, url_id, clicks, last_accessed, created_at from statistics where url_id = $1 order by id
`

func (q *Queries) GetStatisticsByUrlId(ctx context.Context, urlID int64) (*Statistic, error) {
	row := q.db.QueryRow(ctx, getStatisticsByUrlId, urlID)
	var i Statistic
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.Clicks,
		&i.LastAccessed,
		&i.CreatedAt,
	)
	return &i, err
}

const incrementClicksCountById = `-- name: IncrementClicksCountById :one
update statistics set access_count = access_count + 1 where id = $1 returning id, url_id, clicks, last_accessed, created_at
`

func (q *Queries) IncrementClicksCountById(ctx context.Context, id int64) (*Statistic, error) {
	row := q.db.QueryRow(ctx, incrementClicksCountById, id)
	var i Statistic
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.Clicks,
		&i.LastAccessed,
		&i.CreatedAt,
	)
	return &i, err
}

const incrementClicksCountByUrlId = `-- name: IncrementClicksCountByUrlId :one
update statistics set access_count = access_count + 1 where url_id = $1 returning id, url_id, clicks, last_accessed, created_at
`

func (q *Queries) IncrementClicksCountByUrlId(ctx context.Context, urlID int64) (*Statistic, error) {
	row := q.db.QueryRow(ctx, incrementClicksCountByUrlId, urlID)
	var i Statistic
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.Clicks,
		&i.LastAccessed,
		&i.CreatedAt,
	)
	return &i, err
}

const listStatistics = `-- name: ListStatistics :many
select id, url_id, clicks, last_accessed, created_at from statistics order by id limit $1 offset $2
`

type ListStatisticsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStatistics(ctx context.Context, arg ListStatisticsParams) ([]*Statistic, error) {
	rows, err := q.db.Query(ctx, listStatistics, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Statistic
	for rows.Next() {
		var i Statistic
		if err := rows.Scan(
			&i.ID,
			&i.UrlID,
			&i.Clicks,
			&i.LastAccessed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastAccessedById = `-- name: UpdateLastAccessedById :one
update statistics set last_accessed = now() where id = $1 returning id, url_id, clicks, last_accessed, created_at
`

func (q *Queries) UpdateLastAccessedById(ctx context.Context, id int64) (*Statistic, error) {
	row := q.db.QueryRow(ctx, updateLastAccessedById, id)
	var i Statistic
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.Clicks,
		&i.LastAccessed,
		&i.CreatedAt,
	)
	return &i, err
}

const updateLastAccessedByUrlId = `-- name: UpdateLastAccessedByUrlId :one
update statistics set last_accessed = now() where url_id = $1 returning id, url_id, clicks, last_accessed, created_at
`

func (q *Queries) UpdateLastAccessedByUrlId(ctx context.Context, urlID int64) (*Statistic, error) {
	row := q.db.QueryRow(ctx, updateLastAccessedByUrlId, urlID)
	var i Statistic
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.Clicks,
		&i.LastAccessed,
		&i.CreatedAt,
	)
	return &i, err
}
