// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package db

import (
	"context"
)

const createUrl = `-- name: CreateUrl :one
insert into urls (original_url, short_url) values ($1, $2) ON CONFLICT (short_url) DO NOTHING returning id, original_url, short_url, created_at
`

type CreateUrlParams struct {
	OriginalUrl string `json:"original_url"`
	ShortUrl    string `json:"short_url"`
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) (*Url, error) {
	row := q.db.QueryRow(ctx, createUrl, arg.OriginalUrl, arg.ShortUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteUrlById = `-- name: DeleteUrlById :exec
delete from urls where id = $1
`

func (q *Queries) DeleteUrlById(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUrlById, id)
	return err
}

const deleteUrlByShortUrl = `-- name: DeleteUrlByShortUrl :exec
delete from urls where short_url = $1
`

func (q *Queries) DeleteUrlByShortUrl(ctx context.Context, shortUrl string) error {
	_, err := q.db.Exec(ctx, deleteUrlByShortUrl, shortUrl)
	return err
}

const getOriginalUrlById = `-- name: GetOriginalUrlById :one
select original_url from urls where id = $1
`

func (q *Queries) GetOriginalUrlById(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getOriginalUrlById, id)
	var original_url string
	err := row.Scan(&original_url)
	return original_url, err
}

const getOriginalUrlByShortUrl = `-- name: GetOriginalUrlByShortUrl :one
select original_url from urls where short_url = $1
`

func (q *Queries) GetOriginalUrlByShortUrl(ctx context.Context, shortUrl string) (string, error) {
	row := q.db.QueryRow(ctx, getOriginalUrlByShortUrl, shortUrl)
	var original_url string
	err := row.Scan(&original_url)
	return original_url, err
}

const getUrls = `-- name: GetUrls :many
select id, original_url, short_url, created_at from urls order by id
`

func (q *Queries) GetUrls(ctx context.Context) ([]*Url, error) {
	rows, err := q.db.Query(ctx, getUrls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUrls = `-- name: ListUrls :many
select id, original_url, short_url, created_at from urls order by id limit $1 offset $2
`

type ListUrlsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUrls(ctx context.Context, arg ListUrlsParams) ([]*Url, error) {
	rows, err := q.db.Query(ctx, listUrls, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
