// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_agents.sql

package db

import (
	"context"
)

const createUserAgent = `-- name: CreateUserAgent :one
insert into user_agents (fingerprint_id, agent) values ($1, $2) returning id, fingerprint_id, agent, last_accessed
`

type CreateUserAgentParams struct {
	FingerprintID int64  `json:"fingerprint_id"`
	Agent         string `json:"agent"`
}

func (q *Queries) CreateUserAgent(ctx context.Context, arg CreateUserAgentParams) (*UserAgent, error) {
	row := q.db.QueryRow(ctx, createUserAgent, arg.FingerprintID, arg.Agent)
	var i UserAgent
	err := row.Scan(
		&i.ID,
		&i.FingerprintID,
		&i.Agent,
		&i.LastAccessed,
	)
	return &i, err
}

const getUserAgentById = `-- name: GetUserAgentById :one
select id, fingerprint_id, agent, last_accessed from user_agents where id = $1
`

func (q *Queries) GetUserAgentById(ctx context.Context, id int64) (*UserAgent, error) {
	row := q.db.QueryRow(ctx, getUserAgentById, id)
	var i UserAgent
	err := row.Scan(
		&i.ID,
		&i.FingerprintID,
		&i.Agent,
		&i.LastAccessed,
	)
	return &i, err
}

const getUserAgents = `-- name: GetUserAgents :many
select id, fingerprint_id, agent, last_accessed from user_agents order by id
`

func (q *Queries) GetUserAgents(ctx context.Context) ([]*UserAgent, error) {
	rows, err := q.db.Query(ctx, getUserAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*UserAgent
	for rows.Next() {
		var i UserAgent
		if err := rows.Scan(
			&i.ID,
			&i.FingerprintID,
			&i.Agent,
			&i.LastAccessed,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAgentsByFingerprintId = `-- name: GetUserAgentsByFingerprintId :many
select id, fingerprint_id, agent, last_accessed from user_agents where fingerprint_id = $1
`

func (q *Queries) GetUserAgentsByFingerprintId(ctx context.Context, fingerprintID int64) ([]*UserAgent, error) {
	rows, err := q.db.Query(ctx, getUserAgentsByFingerprintId, fingerprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*UserAgent
	for rows.Next() {
		var i UserAgent
		if err := rows.Scan(
			&i.ID,
			&i.FingerprintID,
			&i.Agent,
			&i.LastAccessed,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserAgentLastAccessedById = `-- name: UpdateUserAgentLastAccessedById :one
update user_agents set last_accessed = now() where id = $1 returning id, fingerprint_id, agent, last_accessed
`

func (q *Queries) UpdateUserAgentLastAccessedById(ctx context.Context, id int64) (*UserAgent, error) {
	row := q.db.QueryRow(ctx, updateUserAgentLastAccessedById, id)
	var i UserAgent
	err := row.Scan(
		&i.ID,
		&i.FingerprintID,
		&i.Agent,
		&i.LastAccessed,
	)
	return &i, err
}
